spring:
  datasource:
    url: jdbc:h2:mem:devdb
  sql:
    init:
      platform: h2
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

server:
  port: 9311
  
logging:
  level:
    '[com.skillstorm]': debug
    root: info
  
#We'll come back to this  
skillstorm:
  race:
    champion: Marcie